fix: exclude old org.jboss.netty classes
The akka-remote transitive dependency brings an older io.netty jar into
the assembly causing an occasional "Wrong return type in function"
exception starting SJS:

```
[sparkDriver-akka.actor.default-dispatcher-2] ERROR akka.actor.ActorSystemImpl - Uncaught fatal error from thread [sparkDriver-akka.remote.default-remote-dispatcher-5] shutting down ActorSystem [sparkDriver]
java.lang.VerifyError: (class: org/jboss/netty/channel/socket/nio/NioWorkerPool, method: createWorker signature: (Ljava/util/concurrent/Executor;)Lorg/jboss/netty/channel/socket/nio/AbstractNioWorker;) Wrong return type in function
```

See <https://github.com/sbt/sbt/issues/1518> why the simple exclude of
akka-remote does not work.